# Generated by Django 5.2.17 on 2026-09-10 17:56

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="farms/")),
                ("photo_url", models.URLField(blank=True)),
                ("story", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("crop", "Crop"), ("animal", "Animal")],
                        default="crop",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=250,
                        help_text="EGP charged to adopt one share of this batch.",
                        max_digits=10,
                    ),
                ),
                (
                    "share_size_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Kg delivered per adopted share.",
                        max_digits=10,
                    ),
                ),
                ("planted_date", models.DateField()),
                ("expected_harvest_date", models.DateField()),
                (
                    "qr_code",
                    models.CharField(
                        default=core.models.generate_qr_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="batches/"),
                ),
                ("photo_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "batches",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("harvest", "Harvest"),
                            ("cold_storage", "Cold Storage"),
                            ("transport", "Transport"),
                            ("market", "Market"),
                            ("delivered", "Delivered"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_ok", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity_damaged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("photo_url", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.batch",
                    ),
                ),
            ],
            options={
                "ordering": ("timestamp",),
            },
        ),
        migrations.CreateModel(
            name="ConsumerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_committed",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="core.batch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "batch"), name="unique_subscription_per_batch"
                    )
                ],
            },
        ),
    ]
