# Generated by Django 5.2.17 on 2026-09-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="crop_type_ar",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="batch",
            name="description_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="location_ar",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="farm",
            name="name_ar",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="farm",
            name="story_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="location_ar",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
